#include "kvant/tax/sweden.hpp"
#include <algorithm>
#include <numeric>
#include <stdexcept>
namespace kvant::tax {using money::Fixed;namespace {Fixed zero(){return{0,100};}}
SwedishTaxLedger::SwedishTaxLedger(AccountType t,std::vector<RuleVersion>r):type_(t),rules_(std::move(r)){if(rules_.empty())throw std::invalid_argument("rules");}
void SwedishTaxLedger::acquire(Lot l){if(l.quantity.raw()<=0||l.cost_sek.raw()<0||l.quantity.scale()!=money::quantity_scale||l.cost_sek.scale()!=100)throw std::invalid_argument("lot scales");lots_.push_back(std::move(l));}
Disposal SwedishTaxLedger::dispose(const std::string&a,Fixed qty,Fixed proceeds,LotMethod method,const std::vector<std::string>&ids){if(qty.raw()<=0||qty.scale()!=money::quantity_scale||proceeds.scale()!=100)throw std::invalid_argument("disposal");std::vector<std::size_t>idx;for(std::size_t i=0;i<lots_.size();++i)if(lots_[i].asset_id==a&&lots_[i].quantity.raw()>0)idx.push_back(i);if(method==LotMethod::fifo)std::sort(idx.begin(),idx.end(),[&](auto x,auto y){return lots_[x].acquired_at<lots_[y].acquired_at;});else if(method==LotMethod::lifo)std::sort(idx.begin(),idx.end(),[&](auto x,auto y){return lots_[x].acquired_at>lots_[y].acquired_at;});else if(method==LotMethod::hifo)std::sort(idx.begin(),idx.end(),[&](auto x,auto y){return lots_[x].cost_sek.decimal()/lots_[x].quantity.decimal()>lots_[y].cost_sek.decimal()/lots_[y].quantity.decimal();});else if(method==LotMethod::specific_id)std::sort(idx.begin(),idx.end(),[&](auto x,auto y){auto px=std::find(ids.begin(),ids.end(),lots_[x].id),py=std::find(ids.begin(),ids.end(),lots_[y].id);return px<py;});
Fixed cost=zero();std::vector<std::string>used;auto remaining=qty;if(method==LotMethod::average_cost){long double totalq=0,totalc=0;for(auto i:idx){totalq+=lots_[i].quantity.decimal();totalc+=lots_[i].cost_sek.decimal();}if(totalq+1e-12<qty.decimal())throw std::runtime_error("insufficient quantity");cost=Fixed::from_decimal(totalc*qty.decimal()/totalq,100);long double ratio=qty.decimal()/totalq;for(auto i:idx){auto take=lots_[i].quantity.decimal()*ratio;lots_[i].quantity=Fixed::from_decimal(lots_[i].quantity.decimal()-take,money::quantity_scale);lots_[i].cost_sek=Fixed::from_decimal(lots_[i].cost_sek.decimal()*(1-ratio),100);used.push_back(lots_[i].id);}remaining={0,money::quantity_scale};}else for(auto i:idx){if(remaining.raw()==0)break;long double take=std::min(remaining.decimal(),lots_[i].quantity.decimal()),fraction=take/lots_[i].quantity.decimal();cost=cost+Fixed::from_decimal(lots_[i].cost_sek.decimal()*fraction,100);lots_[i].quantity=Fixed::from_decimal(lots_[i].quantity.decimal()-take,money::quantity_scale);lots_[i].cost_sek=Fixed::from_decimal(lots_[i].cost_sek.decimal()*(1-fraction),100);remaining=Fixed::from_decimal(remaining.decimal()-take,money::quantity_scale);used.push_back(lots_[i].id);}if(remaining.raw()!=0)throw std::runtime_error("insufficient quantity");Fixed gain=proceeds-cost;if(type_==AccountType::taxable)realized_=realized_+gain;return{proceeds,cost,gain,used};}
void SwedishTaxLedger::record_dividend(Fixed g,Fixed w){dividends_=dividends_+g;withholding_=withholding_+w;}void SwedishTaxLedger::record_interest(Fixed i,Fixed e){interest_income_=interest_income_+i;interest_expense_=interest_expense_+e;}void SwedishTaxLedger::record_fx_gain(Fixed r,Fixed u){fx_realized_=fx_realized_+r;fx_unrealized_=fx_unrealized_+u;}
Fixed SwedishTaxLedger::isk_capital_base(const std::vector<IskQuarter>&q)const{if(q.size()!=4)throw std::invalid_argument("four quarters required");Fixed sum=zero();for(auto&x:q)sum=sum+x.opening_value_sek+x.deposits_sek;return Fixed::from_decimal(sum.decimal()/4,100);}
RuleVersion SwedishTaxLedger::rule(int y)const{for(auto&r:rules_)if(r.tax_year==y)return r;throw std::out_of_range("missing tax rule year");}
Fixed SwedishTaxLedger::estimated_tax(int y)const{auto r=rule(y);if(type_==AccountType::isk){auto it=isk_base_.find(y);if(it==isk_base_.end())return zero();long double taxable=std::max(0.L,it->second.decimal()-r.isk_allowance_sek.decimal());return Fixed::from_decimal(taxable*r.isk_standard_rate.decimal()*r.capital_tax_rate.decimal(),100);}long double taxable=realized_.decimal()+dividends_.decimal()+interest_income_.decimal()-interest_expense_.decimal()+fx_realized_.decimal();return Fixed::from_decimal(std::max(0.L,taxable)*r.capital_tax_rate.decimal()-withholding_.decimal(),100);}
}
