#include "kvant/monitoring/metrics.hpp"
#include <cmath>
#include <numeric>
#include <stdexcept>
namespace kvant::monitoring {namespace {
void pairs(std::span<const double>a,std::span<const double>b,std::size_t minimum=1){if(a.size()!=b.size()||a.size()<minimum)throw std::invalid_argument("invalid paired series");for(double x:a)if(!std::isfinite(x))throw std::invalid_argument("non-finite series");for(double x:b)if(!std::isfinite(x))throw std::invalid_argument("non-finite series");}
}
double pearson_information_coefficient(std::span<const double>x,std::span<const double>y){pairs(x,y,2);double mx=0,my=0,c=0,vx=0,vy=0;std::size_t n=0;for(std::size_t i=0;i<x.size();++i){++n;double dx=x[i]-mx,dy=y[i]-my;mx+=dx/n;my+=dy/n;c+=dx*(y[i]-my);vx+=dx*(x[i]-mx);vy+=dy*(y[i]-my);}if(vx<=0||vy<=0)throw std::domain_error("IC undefined for constant series");return c/std::sqrt(vx*vy);}
double information_ratio(std::span<const double>r,double periods){if(r.size()<2||periods<=0)throw std::invalid_argument("invalid IR inputs");double m=0,m2=0;std::size_t n=0;for(double x:r){if(!std::isfinite(x))throw std::invalid_argument("non-finite return");++n;double d=x-m;m+=d/n;m2+=d*(x-m);}double sd=std::sqrt(m2/(n-1));if(sd==0)throw std::domain_error("IR undefined for zero tracking error");return m/sd*std::sqrt(periods);}
double brier_score(std::span<const double>p,std::span<const double>y){pairs(p,y);double s=0;for(std::size_t i=0;i<p.size();++i){if(p[i]<0||p[i]>1||(y[i]!=0&&y[i]!=1))throw std::invalid_argument("invalid Brier inputs");double d=p[i]-y[i];s+=d*d;}return s/p.size();}
double mean_live_backtest_divergence(std::span<const double>live,std::span<const double>back){pairs(live,back);double s=0;for(std::size_t i=0;i<live.size();++i)s+=live[i]-back[i];return s/live.size();}
double alpha_decay_half_life(std::span<const double>h,std::span<const double>ic){pairs(h,ic,2);double sx=0,sy=0,sxx=0,sxy=0;std::size_t n=0;for(std::size_t i=0;i<h.size();++i){if(h[i]<0||ic[i]<=0)continue;double y=std::log(ic[i]);sx+=h[i];sy+=y;sxx+=h[i]*h[i];sxy+=h[i]*y;++n;}if(n<2)throw std::domain_error("need positive IC at two horizons");double den=n*sxx-sx*sx;if(std::abs(den)<1e-15)throw std::domain_error("decay horizons are singular");double slope=(n*sxy-sx*sy)/den;if(slope>=0)throw std::domain_error("alpha does not exhibit exponential decay");return std::log(2.0)/-slope;}
std::vector<MetricPoint> rolling_ic(std::span<const Observation>o,std::size_t window){if(window<2||o.size()<window)throw std::invalid_argument("invalid rolling window");std::vector<MetricPoint>out;std::vector<double>x(window),y(window);for(std::size_t end=window;end<=o.size();++end){for(std::size_t j=0;j<window;++j){x[j]=o[end-window+j].prediction;y[j]=o[end-window+j].actual;}out.push_back({o[end-1].timestamp,pearson_information_coefficient(x,y),window});}return out;}
MonitoringSnapshot snapshot(std::span<const Observation>o,double periods,std::span<const double>h,std::span<const double>ics){if(o.size()<2)throw std::invalid_argument("insufficient observations");std::vector<double>p,a,prob,binary,active,live,back;p.reserve(o.size());for(const auto&v:o){p.push_back(v.prediction);a.push_back(v.actual);prob.push_back(v.probability);binary.push_back(v.actual>0?1:0);active.push_back(v.live_return-v.backtest_return);live.push_back(v.live_return);back.push_back(v.backtest_return);}return{pearson_information_coefficient(p,a),information_ratio(active,periods),brier_score(prob,binary),mean_live_backtest_divergence(live,back),alpha_decay_half_life(h,ics),o.size()};}
}
