#include "kvant/control/self_correction.hpp"
#include <cmath>
#include <fstream>
#include <nlohmann/json.hpp>
#include <stdexcept>
namespace kvant::control {
SelfCorrectionLoop::SelfCorrectionLoop(Journal&j,Policy p,PageHinkley ph,Cusum c,std::filesystem::path q):journal_(j),policy_(p),page_hinkley_(std::move(ph)),cusum_(std::move(c)),retrain_queue_(std::move(q)){if(!policy_.cooldown_days||!policy_.shadow_minimum_observations||policy_.shadow_required_improvement<0)throw std::invalid_argument("invalid correction policy");std::filesystem::create_directories(retrain_queue_);}
void SelfCorrectionLoop::predict(const PredictionRecord&r){if(r.prediction_id.empty()||r.model_version.empty()||r.resolve_after<r.made_at||!std::isfinite(r.prediction)||!std::isfinite(r.lower)||!std::isfinite(r.upper)||r.lower>r.upper)throw std::invalid_argument("invalid prediction record");journal_.log_prediction(r);}
Decision SelfCorrectionLoop::resolve(const PredictionRecord&p,double actual,std::int64_t at,std::size_t day,AdjustmentTier tier){if(at<p.resolve_after||!std::isfinite(actual))throw std::invalid_argument("outcome resolved too early or non-finite");double error=actual-p.prediction;journal_.log_resolution({p.prediction_id,at,actual,error});auto ph=page_hinkley_.update(std::abs(error));auto cu=cusum_.update(error);bool drift=ph.detected||cu.detected;if(!drift)return{};if(last_adjustment_day_&&day<*last_adjustment_day_+policy_.cooldown_days){journal_.log_event(at,"drift_suppressed","cooldown active");return{true,AdjustmentTier::none,false};}last_adjustment_day_=day;page_hinkley_.reset();cusum_.reset();bool retrain=tier==AdjustmentTier::retrain;if(retrain)request_retrain(p,error,at);journal_.log_event(at,"adjustment",std::to_string(static_cast<int>(tier)));return{true,tier,retrain};}
void SelfCorrectionLoop::compare_shadow(const ShadowComparison&r){if(r.incumbent_loss<0||r.candidate_loss<0)throw std::invalid_argument("loss must be nonnegative");journal_.log_shadow(r);++shadow_count_;incumbent_loss_+=r.incumbent_loss;candidate_loss_+=r.candidate_loss;if(shadow_count_>=policy_.shadow_minimum_observations){double incumbent=incumbent_loss_/shadow_count_,candidate=candidate_loss_/shadow_count_;candidate_ready_=candidate<=incumbent*(1-policy_.shadow_required_improvement);}}
bool SelfCorrectionLoop::candidate_can_control()const noexcept{return candidate_ready_;}
void SelfCorrectionLoop::promote_candidate(const std::string&v,std::int64_t t){if(!candidate_ready_||v.empty())throw std::logic_error("candidate has not passed shadow gate");journal_.log_event(t,"model_promoted",v);shadow_count_=0;incumbent_loss_=candidate_loss_=0;candidate_ready_=false;}
void SelfCorrectionLoop::request_retrain(const PredictionRecord&p,double error,std::int64_t at){nlohmann::json j={{"schema_version",1},{"requested_at",at},{"model_version",p.model_version},{"symbol",p.symbol},{"trigger_error",error},{"status","pending"}};auto final=retrain_queue_/(p.prediction_id+".json"),tmp=final;tmp+=".tmp";std::ofstream out(tmp);out<<j.dump(2);out.close();std::filesystem::rename(tmp,final);}
}
