#include "kvant/persistence/duckdb_store.hpp"
#include <stdexcept>
#ifdef KVANT_WITH_DUCKDB
#include <duckdb.h>
namespace kvant::persistence {namespace {void ok(duckdb_state s,const char*m){if(s==DuckDBError)throw std::runtime_error(m);}std::string text(duckdb_result*r,idx_t c,idx_t row){char*v=duckdb_value_varchar(r,c,row);if(!v)return{};std::string out(v);duckdb_free(v);return out;}void exec(duckdb_connection c,const char*s){duckdb_result r{};ok(duckdb_query(c,s,&r),duckdb_result_error(&r));duckdb_destroy_result(&r);}}
struct DuckDbStore::Impl{duckdb_database db{};duckdb_connection c{};};DuckDbStore::DuckDbStore(const std::filesystem::path&p):p_(std::make_unique<Impl>()){ok(duckdb_open(p.c_str(),&p_->db),"open failed");ok(duckdb_connect(p_->db,&p_->c),"connect failed");}DuckDbStore::~DuckDbStore(){if(p_){duckdb_disconnect(&p_->c);duckdb_close(&p_->db);}}DuckDbStore::DuckDbStore(DuckDbStore&&)noexcept=default;
void DuckDbStore::migrate(){exec(p_->c,"CREATE TABLE IF NOT EXISTS predictions(id VARCHAR PRIMARY KEY,model VARCHAR,symbol VARCHAR,made_at BIGINT,resolve_after BIGINT,value DOUBLE,lower DOUBLE,upper DOUBLE,features JSON,shadow BOOLEAN); CREATE TABLE IF NOT EXISTS resolutions(id VARCHAR PRIMARY KEY,resolved_at BIGINT,actual DOUBLE,error DOUBLE); CREATE TABLE IF NOT EXISTS experiments(run_id VARCHAR PRIMARY KEY,git_commit VARCHAR,parameters JSON,metrics JSON,variants UINTEGER,created_at TIMESTAMP DEFAULT current_timestamp);");}
void DuckDbStore::append_prediction(const Prediction&x){duckdb_prepared_statement s{};ok(duckdb_prepare(p_->c,"INSERT INTO predictions VALUES (?,?,?,?,?,?,?,?,?,?)",&s),"prepare");duckdb_bind_varchar(s,1,x.id.c_str());duckdb_bind_varchar(s,2,x.model.c_str());duckdb_bind_varchar(s,3,x.symbol.c_str());duckdb_bind_int64(s,4,x.made_at);duckdb_bind_int64(s,5,x.resolve_after);duckdb_bind_double(s,6,x.value);duckdb_bind_double(s,7,x.lower);duckdb_bind_double(s,8,x.upper);duckdb_bind_varchar(s,9,x.features_json.c_str());duckdb_bind_boolean(s,10,x.shadow);duckdb_result r{};auto state=duckdb_execute_prepared(s,&r);duckdb_destroy_prepare(&s);if(state==DuckDBError){auto e=std::string(duckdb_result_error(&r));duckdb_destroy_result(&r);throw std::runtime_error(e);}duckdb_destroy_result(&r);}
void DuckDbStore::resolve_prediction(const std::string&id,long long t,double a,double e){duckdb_prepared_statement s{};ok(duckdb_prepare(p_->c,"INSERT INTO resolutions VALUES (?,?,?,?)",&s),"prepare");duckdb_bind_varchar(s,1,id.c_str());duckdb_bind_int64(s,2,t);duckdb_bind_double(s,3,a);duckdb_bind_double(s,4,e);duckdb_result r{};ok(duckdb_execute_prepared(s,&r),"resolution insert");duckdb_destroy_result(&r);duckdb_destroy_prepare(&s);}
void DuckDbStore::append_experiment(const std::string&id,const std::string&git,const std::string&par,const std::string&met,unsigned v){duckdb_prepared_statement s{};ok(duckdb_prepare(p_->c,"INSERT INTO experiments(run_id,git_commit,parameters,metrics,variants) VALUES (?,?,?,?,?)",&s),"prepare");duckdb_bind_varchar(s,1,id.c_str());duckdb_bind_varchar(s,2,git.c_str());duckdb_bind_varchar(s,3,par.c_str());duckdb_bind_varchar(s,4,met.c_str());duckdb_bind_uint32(s,5,v);duckdb_result r{};ok(duckdb_execute_prepared(s,&r),"experiment insert");duckdb_destroy_result(&r);duckdb_destroy_prepare(&s);}
std::vector<Prediction>DuckDbStore::unresolved(long long t)const{duckdb_prepared_statement s{};ok(duckdb_prepare(p_->c,"SELECT p.* FROM predictions p LEFT JOIN resolutions r ON p.id=r.id WHERE r.id IS NULL AND p.resolve_after<=? ORDER BY p.resolve_after",&s),"prepare");duckdb_bind_int64(s,1,t);duckdb_result r{};ok(duckdb_execute_prepared(s,&r),"query");std::vector<Prediction>out;auto rows=duckdb_row_count(&r);for(idx_t i=0;i<rows;++i){out.push_back({text(&r,0,i),text(&r,1,i),text(&r,2,i),text(&r,8,i),duckdb_value_int64(&r,3,i),duckdb_value_int64(&r,4,i),duckdb_value_double(&r,5,i),duckdb_value_double(&r,6,i),duckdb_value_double(&r,7,i),bool(duckdb_value_boolean(&r,9,i))});}duckdb_destroy_result(&r);duckdb_destroy_prepare(&s);return out;}}
#else
namespace kvant::persistence {struct DuckDbStore::Impl{};DuckDbStore::DuckDbStore(const std::filesystem::path&):p_(std::make_unique<Impl>()){}DuckDbStore::~DuckDbStore()=default;DuckDbStore::DuckDbStore(DuckDbStore&&)noexcept=default;void DuckDbStore::migrate(){throw std::runtime_error("DuckDB disabled");}void DuckDbStore::append_prediction(const Prediction&){throw std::runtime_error("DuckDB disabled");}void DuckDbStore::resolve_prediction(const std::string&,long long,double,double){throw std::runtime_error("DuckDB disabled");}void DuckDbStore::append_experiment(const std::string&,const std::string&,const std::string&,const std::string&,unsigned){throw std::runtime_error("DuckDB disabled");}std::vector<Prediction>DuckDbStore::unresolved(long long)const{throw std::runtime_error("DuckDB disabled");}}
#endif
