#include "kvant/risk/osqp_optimizer.hpp"
#include <stdexcept>
#ifdef KVANT_WITH_OSQP
#include <osqp.h>
#include <vector>
namespace kvant::risk {namespace {struct Csc{std::vector<c_int>p,i;std::vector<c_float>x;csc*view{};Csc()=default;Csc(const Csc&)=delete;Csc&operator=(const Csc&)=delete;Csc(Csc&&o)noexcept:p(std::move(o.p)),i(std::move(o.i)),x(std::move(o.x)),view(o.view){o.view=nullptr;}Csc&operator=(Csc&&o)noexcept{if(this!=&o){if(view)c_free(view);p=std::move(o.p);i=std::move(o.i);x=std::move(o.x);view=o.view;o.view=nullptr;}return*this;}~Csc(){if(view)c_free(view);} };Csc dense_csc(const Eigen::MatrixXd&m,bool upper=false){Csc c;c.p.push_back(0);for(Eigen::Index col=0;col<m.cols();++col){for(Eigen::Index row=0;row<m.rows();++row){if((!upper||row<=col)&&m(row,col)!=0){c.i.push_back(row);c.x.push_back(m(row,col));}}c.p.push_back(c.i.size());}c.view=csc_matrix(m.rows(),m.cols(),c.x.size(),c.x.data(),c.i.data(),c.p.data());return c;}}
OsqpResult solve_osqp(const Eigen::MatrixXd&S,const Eigen::VectorXd&mu,const Eigen::VectorXd&w0,const Eigen::VectorXd&cost,const Limits&lim,double lambda){const c_int n=mu.size();if(n==0||S.rows()!=n||S.cols()!=n||w0.size()!=n||cost.size()!=n||lim.lower.size()!=n||lim.upper.size()!=n)throw std::invalid_argument("QP dimensions");const c_int vars=3*n;const c_int sectors=lim.sector_exposure.rows();const c_int rows=2+6*n+sectors;Eigen::MatrixXd P=Eigen::MatrixXd::Zero(vars,vars);P.topLeftCorner(n,n)=2*lambda*S;Eigen::VectorXd q=Eigen::VectorXd::Zero(vars);q.head(n)=-mu;q.segment(n,n)=cost;Eigen::MatrixXd A=Eigen::MatrixXd::Zero(rows,vars);Eigen::VectorXd l=Eigen::VectorXd::Constant(rows,-OSQP_INFTY),u=Eigen::VectorXd::Constant(rows,OSQP_INFTY);int r=0;A.block(r,0,1,n).setOnes();l[r]=u[r]=1;++r;for(int j=0;j<n;++j){A(r,j)=1;l[r]=lim.lower[j];u[r]=lim.upper[j];++r;}for(int j=0;j<n;++j){A(r,j)=1;A(r,n+j)=-1;u[r]=w0[j];++r;A(r,j)=-1;A(r,n+j)=-1;u[r]=-w0[j];++r;}for(int j=0;j<n;++j){A(r,n+j)=1;l[r]=0;++r;}for(int j=0;j<n;++j){A(r,j)=1;A(r,2*n+j)=-1;u[r]=0;++r;}for(int j=0;j<n;++j){A(r,j)=-1;A(r,2*n+j)=-1;u[r]=0;++r;}A.block(r,2*n,1,n).setOnes();u[r]=lim.gross_leverage;++r;if(sectors){A.block(r,0,sectors,n)=lim.sector_exposure;u.segment(r,sectors)=lim.sector_caps;r+=sectors;}auto pc=dense_csc(P,true),ac=dense_csc(A);OSQPData data{};data.n=vars;data.m=r;data.P=pc.view;data.q=q.data();data.A=ac.view;data.l=l.data();data.u=u.data();OSQPSettings settings;osqp_set_default_settings(&settings);settings.verbose=0;settings.polish=1;OSQPWorkspace*work=osqp_setup(&data,&settings);if(!work)throw std::runtime_error("OSQP setup failed");osqp_solve(work);OsqpResult out;out.status=work->info->status_val;out.objective=work->info->obj_val;out.primal_residual=work->info->pri_res;out.dual_residual=work->info->dua_res;if(work->solution&&work->solution->x)out.weights=Eigen::Map<Eigen::VectorXd>(work->solution->x,n);osqp_cleanup(work);return out;}}
#else
namespace kvant::risk {OsqpResult solve_osqp(const Eigen::MatrixXd&,const Eigen::VectorXd&,const Eigen::VectorXd&,const Eigen::VectorXd&,const Limits&,double){throw std::runtime_error("OSQP disabled");}}
#endif
