#include "kvant/stats/stationarity.hpp"
#include <algorithm>
#include <cmath>
#include <stdexcept>
#include <vector>

namespace kvant::stats {
namespace {
using Matrix=std::vector<std::vector<double>>;
std::vector<double> solve(Matrix a,std::vector<double>b){const std::size_t n=b.size();for(std::size_t i=0;i<n;++i){std::size_t p=i;for(std::size_t j=i+1;j<n;++j)if(std::abs(a[j][i])>std::abs(a[p][i]))p=j;if(std::abs(a[p][i])<1e-12)throw std::domain_error("singular regression");std::swap(a[i],a[p]);std::swap(b[i],b[p]);double d=a[i][i];for(std::size_t k=i;k<n;++k)a[i][k]/=d;b[i]/=d;for(std::size_t j=0;j<n;++j)if(j!=i){double f=a[j][i];for(std::size_t k=i;k<n;++k)a[j][k]-=f*a[i][k];b[j]-=f*b[i];}}return b;}
struct Ols{std::vector<double> beta;Matrix inv;double sigma2;};
Ols ols(const Matrix&x,const std::vector<double>&y){std::size_t n=x.size(),k=x[0].size();if(n<=k)throw std::invalid_argument("insufficient regression degrees of freedom");Matrix xtx(k,std::vector<double>(k));std::vector<double>xty(k);for(std::size_t i=0;i<n;++i)for(std::size_t a=0;a<k;++a){xty[a]+=x[i][a]*y[i];for(std::size_t b=0;b<k;++b)xtx[a][b]+=x[i][a]*x[i][b];}auto beta=solve(xtx,xty);Matrix inv(k,std::vector<double>(k));for(std::size_t j=0;j<k;++j){std::vector<double>e(k);e[j]=1;auto col=solve(xtx,e);for(std::size_t i=0;i<k;++i)inv[i][j]=col[i];}double rss=0;for(std::size_t i=0;i<n;++i){double fit=0;for(std::size_t j=0;j<k;++j)fit+=x[i][j]*beta[j];rss+=(y[i]-fit)*(y[i]-fit);}return{beta,inv,rss/static_cast<double>(n-k)};}
void validate(std::span<const double>x){if(x.size()<8)throw std::invalid_argument("need at least eight finite observations");for(double v:x)if(!std::isfinite(v))throw std::invalid_argument("non-finite observation");}
}
StationarityResult augmented_dickey_fuller(std::span<const double>x,std::size_t p,Deterministic d){validate(x);if(p+4>=x.size())throw std::invalid_argument("too many lags");std::vector<double>dx(x.size()-1);for(std::size_t i=1;i<x.size();++i)dx[i-1]=x[i]-x[i-1];Matrix X;std::vector<double>y;for(std::size_t t=p;t<dx.size();++t){std::vector<double>row;row.push_back(x[t]);if(d!=Deterministic::none)row.push_back(1);if(d==Deterministic::constant_and_trend)row.push_back(static_cast<double>(t+1));for(std::size_t j=1;j<=p;++j)row.push_back(dx[t-j]);X.push_back(row);y.push_back(dx[t]);}auto o=ols(X,y);double stat=o.beta[0]/std::sqrt(o.sigma2*o.inv[0][0]);double c10,c5,c1;if(d==Deterministic::none){c10=-1.62;c5=-1.95;c1=-2.58;}else if(d==Deterministic::constant){c10=-2.57;c5=-2.86;c1=-3.43;}else{c10=-3.13;c5=-3.41;c1=-3.96;}return{stat,c10,c5,c1,stat<c5,X.size(),p};}
StationarityResult kpss(std::span<const double>x,std::size_t bw,Deterministic d){validate(x);if(d==Deterministic::none)throw std::invalid_argument("KPSS requires constant or constant_and_trend");if(bw==0)bw=static_cast<std::size_t>(std::floor(4*std::pow(static_cast<double>(x.size())/100.0,0.25)));bw=std::max<std::size_t>(1,bw);if(bw>=x.size())throw std::invalid_argument("bandwidth too large");Matrix X;std::vector<double>y(x.begin(),x.end());for(std::size_t i=0;i<x.size();++i){std::vector<double>r{1};if(d==Deterministic::constant_and_trend)r.push_back(static_cast<double>(i+1));X.push_back(r);}auto o=ols(X,y);std::vector<double>e(x.size());for(std::size_t i=0;i<x.size();++i){double fit=o.beta[0];if(d==Deterministic::constant_and_trend)fit+=o.beta[1]*static_cast<double>(i+1);e[i]=x[i]-fit;}double s=0,eta=0;for(double v:e){s+=v;eta+=s*s;}double lrv=0;for(double v:e)lrv+=v*v;lrv/=static_cast<double>(e.size());for(std::size_t lag=1;lag<=bw;++lag){double cov=0;for(std::size_t t=lag;t<e.size();++t)cov+=e[t]*e[t-lag];cov/=static_cast<double>(e.size());lrv+=2*(1-static_cast<double>(lag)/static_cast<double>(bw+1))*cov;}if(lrv<=0)throw std::domain_error("non-positive long-run variance");double stat=eta/(static_cast<double>(e.size())*static_cast<double>(e.size())*lrv);double c10,c5,c1;if(d==Deterministic::constant){c10=.347;c5=.463;c1=.739;}else{c10=.119;c5=.146;c1=.216;}return{stat,c10,c5,c1,stat>c5,e.size(),bw};}
} // namespace kvant::stats
